### ISSUE TITLE
Remove any user requests from googleusercontent.com from CMSWEB side. 

### ISSUE THREAD

**Issue by arooshap** [dmwm/deployment#1265]
This feature can be implemented using mod_evasive.conf file that we already have. 

Here is how we define this file:
The configuration file for mod_evasive, an Apache module designed to provide protection against Distributed Denial of Service (DDoS) attacks, has the following parameters:.

```
DOSHashTableSize: The size of the hash table used to track IP addresses and URLs. The default value is 3097, but you can adjust this value based on the size of your site and the number of clients you expect to handle.

DOSPageInterval: The minimum time in seconds between page requests from the same client. A client that requests the same page more frequently than this value will be blocked. In this configuration, the interval is set to 1 second.

DOSSiteInterval: The minimum time in seconds between requests to different pages from the same client. A client that requests multiple pages more frequently than this value will be blocked. In this configuration, the interval is set to 1 second.

DOSBlockingPeriod: The amount of time in seconds that a client will be blocked after triggering the module's protection. In this configuration, the blocking period is set to 10 seconds.

DOSPageCount: The number of requests for the same page from the same client that will trigger the module's protection. In this configuration, the limit is set to 2 requests.

DOSSiteCount: The number of requests for different pages from the same client that will trigger the module's protection. In this configuration, the limit is set to 50 requests.

DOSSystemCommand: A command that will be executed when a client is blocked. In this configuration, the command will write a log message to a file.

DOSWhitelist: A list of IP addresses that should not be blocked by the module. In this configuration, several CERN IP addresses are whitelisted to ensure that they are not blocked.

```

Action item for CMSWeb team,

- [x] #1267
- [x] Set the following configuration,
```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{HTTP_USER_AGENT} ^.*Googleusercontent.*$ [NC]
RewriteRule .* - [F,L]
</IfModule>
```

Or to simply use fail2ban. In that case, the action items would be:

- [x] Install fair2ban in docker.
- [x] Create a file in the jail.d directory to configure fail2ban to monitor Apache logs.
- [x] In the same directory, create a file defining the `fail regex`.
- [x] Make sure that the log path is properly defined and logs are mounted properly there.

Further tasks:
- [ ] Carry out extensive testing and document the procedure.
- [ ] Explore the possibility of further vulnerabilities.

**Comment by muhammadimranfarooqi** [comment]
Hi @arooshap 

Thanks for creating this issue. As this module `mod_evasive` is not enabled in the frontends, I assume most of the genuine requests might get blocked by considering them generating DDOS attacks. We should first try to get list of all production clients that generate a lot of traffic and put them in exception before testing this.

Cheers
M Imran

**Comment by arooshap** [comment]
@muhammadimranfarooqi Thanks for the suggestion, but we are already taking care of that.

**Comment by arooshap** [comment]
That's why I'm testing this procedure on the test6 cluster, but I am sticking with fail2ban rather than mod_evasive as that's something more advanced.
