### ISSUE TITLE
subscribe to /deployment PRs

### ISSUE THREAD

**Issue by threus** [dmwm/deployment#503]
I would like to be notified when a new PR is submitted for /deployment. Would it be possible to add me to the list of subscribers?
Thanks!
Tomas (CMS DQM core)

**Comment by vanbesien** [comment]
I think you do that by setting yourself as a watcher in Github, no?
At the top right of the Github page for deployment, I see three buttons: "(Un)Watch", "Star" and "Fork".
Just hit the first one.

Broen

**Comment by threus** [comment]
whoa thanks :) I am used for the cmssw procedure, where one could request to watch multiple directories (i.e. /DQM), not the whole cmssw.. but you are right, in this case it's simpler. If I could select only deployment/dqmgui, I would, but no real need.
