### ISSUE TITLE
errors in deploy script?

### ISSUE THREAD

**Issue by ticoann** [dmwm/deployment#579]
Hi Lina,
I was trying to install slc6 version but it is getting wrong architecture. (gcc481)

https://github.com/dmwm/deployment/blob/master/Deploy#L52

Shouldn't it be gcc493?

**Comment by h4d4** [comment]
@ticoann  Hi ticoann, 

I've update the script, can you please test it and let me know how it's going?

**Comment by ticoann** [comment]
Thank you, Lina. It works fine now.
